package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Monday, April 28, 2025 3:43:11 PM IST
*/


// Define the interface within the module
public interface ReverseOperations 
{

  // Define the method that takes a string as input and returns a reversed string
  String reverse_string (String str);
} // interface ReverseOperations
