package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Monday, 5 May, 2025 12:38:38 AM IST
*/


// Define an interface called Reverse
public interface ReverseOperations 
{

  // Define a method called reverse_string that takes a string as input and returns a string
  String reverse_string (String str);
} // interface ReverseOperations
