package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Saturday, May 3, 2025 4:42:40 PM IST
*/


// Define an interface called Reverse
public interface ReverseOperations 
{

  // Define a method called reverse_string that takes a string as input and returns a string
  String reverse_string (String str);
} // interface ReverseOperations
